add structure, Nikita BANDURIN
ok-technopolis-autumn-2022/Nikita_Bandurin pull request #1
Opened 2022-10-03 15:34 UTC by NIKITry

2022-10-05 08:14 UTC, fromanywhere requested changes

2022-10-05 08:14 UTC, fromanywhere commented on hw1.html
> +            <ul style = "list-style-type:none">
убираем инлайновые стили, на лекции про это было
Да, будут точки — ничего страшного

2022-10-05 08:14 UTC, fromanywhere commented on hw1.html
> +                <li><input type = "checkbox"></button>S</button></li>
А где будет текст элемента?

2022-10-05 08:14 UTC, fromanywhere commented on hw1.html
> +                <input type = "button">
Тут нужно подумать про доступность

2022-10-05 08:14 UTC, fromanywhere commented on hw1.html
> +                <button>All</button>
На лекции договорились, что здесь радиокнопки

2022-10-05 08:14 UTC, fromanywhere commented on hw1.html
> +                <button>Clear completed</button>
Нужно собрать фильтр в какую-то группу, чтобы оно было отделено от кнопки clear completed. Стоило бы подумать над тем, как это объяснить скринридеру

2022-10-10 08:59 UTC, fromanywhere requested changes
жду исправления комментариев

2022-10-10 08:59 UTC, fromanywhere commented on hw1.html
> +                <input type = "button">
всё еще нужно подумать про доступность

2022-10-13 18:59 UTC, NIKITry commented on hw1.html
> +                <input type = "button">
Не очень понимаю, что значит доступности в этом контексте

2022-10-13 19:39 UTC, NIKITry commented on hw1.html
> +                <button>All</button>
поправил

2022-10-13 19:42 UTC, NIKITry commented on hw1.html
> +                <button>Clear completed</button>
может, можно в div объединить фильтры, а потом в css как-то пихнуть слева clear completed

2022-10-13 20:07 UTC, NIKITry commented on hw1.html
> +                <li><input type = "checkbox"></button>S</button></li>
исправил

2022-10-13 20:07 UTC, NIKITry commented on hw1.html
> +            <ul style = "list-style-type:none">
убрал

2022-10-13 20:08 UTC, NIKITry commented on hw1.html
> +                <input type = "button">
уже понял, вы наверно про araia-label

2022-10-13 20:08 UTC, NIKITry commented on hw1.html
> +                <button>Clear completed</button>
сделал уже по-другому и закоммитил

2022-10-14 07:08 UTC, fromanywhere requested changes

2022-10-14 07:08 UTC, fromanywhere commented on hw1.html
> +                    <input type = "button">
на кнопках без текста нужен title, чтобы люди и читалки понимали, что делает эта кнопка

2022-10-14 07:08 UTC, fromanywhere commented on hw1.html
> +                    <div class="todo-app__filters-bar">
если этот див — это группировка фильтров, то у него должна быть role и aria-label
А n items left должно быть не в нем, а перед ним

2022-10-14 07:08 UTC, fromanywhere commented on hw1.html
> +                        <span class="action_text">All</span>
тогда уже лучше label с завязкой на radio

2022-10-14 11:57 UTC, NIKITry commented on hw1.html
> +                        <span class="action_text">All</span>
В смысле вместо name у радио кнопок писать label?

2022-10-14 13:33 UTC, fromanywhere commented on hw1.html
> +                        <span class="action_text">All</span>
нет. Вместо тега <span> использовать тег <label с for или иным типом связывания c контролом радио

2022-10-14 15:27 UTC, NIKITry commented on hw1.html
> +                    <input type = "button">
сделано

2022-10-14 15:27 UTC, NIKITry commented on hw1.html
> +                    <div class="todo-app__filters-bar">
согласен

2022-10-14 15:44 UTC, fromanywhere commented on hw1.html
> +                    <input type = "button">
не вижу

2022-10-14 15:45 UTC, fromanywhere approved these changes

2022-10-14 15:46 UTC, NIKITry commented on hw1.html
> +                    <input type = "button">
Забыл запушить, бегу к ноуту, одну секунду

2022-10-14 15:49 UTC, NIKITry commented on hw1.html
> +                    <input type = "button">
Отправил, можно мерджить?

2022-10-14 15:50 UTC, merged