some css and html. DZ-2
ok-technopolis-autumn-2022/Nikita_Bandurin pull request #2
Opened 2022-10-24 17:50 UTC by NIKITry

Не могу разобраться с тем, как сделать скролл элементов внутри списка так, чтобы он не уезжал и не ломал верстку

2022-10-25 10:03 UTC, fromanywhere commented
Пока очень далеко от макета

Попробуйте зафиксировать высоты элементов в пикселях. Что касается горизонтали — мы можем с Вами договориться, что там всё будет в одну строку. Тогда, например, white-space: nowrap и overflow: auto

Это не единственный способ решить проблему

2022-12-05 09:15 UTC, fromanywhere requested changes
Пока всё мимо макета 
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1042969/205599426-e4f26851-c196-4ec6-aea9-ac388736b709.png">

2022-12-05 09:15 UTC, fromanywhere commented on todo_style.css
> +    background-image: url(../Nikita_Bandurin/img/select-all.png);
Тут явно битые пути

2022-12-05 09:15 UTC, fromanywhere commented on todo_style.css
> +    min-height: 64px;
Что будет, если текста станет много?

2022-12-05 09:15 UTC, fromanywhere commented on todo_style.css
> +    flex-grow: 10;
Почему 10?

2022-12-05 09:20 UTC, NIKITry commented on todo_style.css
> +    background-image: url(../Nikita_Bandurin/img/select-all.png);
я не понимаю, в чем проблема, у меня все работает

2022-12-05 09:24 UTC, NIKITry commented on todo_style.css
> +    background-image: url(../Nikita_Bandurin/img/select-all.png);
какой путь надо указать, чтобы он не был битым в такой случае? Загрузить картинки на облако или как?

2022-12-05 09:25 UTC, NIKITry commented on todo_style.css
> +    background-image: url(../Nikita_Bandurin/img/select-all.png);
<img width="1323" alt="Screenshot 2022-12-05 at 12 18 24" src="https://user-images.githubusercontent.com/100494290/205601495-a8f61bed-1ec1-415e-8374-98fd32b47368.png">

2022-12-05 09:28 UTC, NIKITry commented on todo_style.css
> +    flex-grow: 10;
ну я решил для текста выделить flex grow 10, иначе он сильно смещается вправо, так как другие блоки тоже имеют свой flex grow

2022-12-05 09:36 UTC, fromanywhere commented on todo_style.css
> +    background-image: url(../Nikita_Bandurin/img/select-all.png);
В репозитории нет директории /Nikita_Bandurin/ . Нужно использовать более короткие относительные пути
./img/select-all.png должно работать

2022-12-05 09:41 UTC, NIKITry commented on todo_style.css
> +    background-image: url(../Nikita_Bandurin/img/select-all.png);
поправил в комете

2022-12-05 09:42 UTC, NIKITry commented on todo_style.css
> +    min-height: 64px;
он заворачиваться будет, если поставить overflow hidden

2022-12-05 09:44 UTC, NIKITry commented on todo_style.css
> +    min-height: 64px;
ну и к тому же вы советовали зафиксировать высоты в пикселях в комментариях к первому коммиту

2022-12-05 18:53 UTC, NIKITry commented on todo_style.css
> +    flex-grow: 10;
Все поправил вроде

2022-12-08 18:20 UTC, fromanywhere requested changes

2022-12-08 18:20 UTC, fromanywhere commented on todo_style.css
> +    border: 1.4px  #f2f2f2 solid ;
дробные пиксели?

2022-12-08 18:20 UTC, fromanywhere commented on todo_style.css
> +    text-indent: -999px;
этого недостаточно, у меня текст влезает в экран
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/1042969/206533598-3d024014-8ac1-4009-ab21-400bb2dd5bf9.png">

2022-12-08 18:20 UTC, fromanywhere commented on todo_style.css
> +    flex-grow: 10;
А 1 недостаточно?

2022-12-08 18:20 UTC, fromanywhere commented on todo_style.css
> +    min-height: 64px;
В текущем виде получается вот так 
<img width="652" alt="image" src="https://user-images.githubusercontent.com/1042969/206534051-cc4c3468-b37d-4213-bea8-53e00e828e2a.png">
(кружок смещается, кнопки удаления нет)

2022-12-08 18:20 UTC, fromanywhere commented on todo_style.css
> +    display: none;
Из-за display: none до фильтра не добраться с клавиатуры

2022-12-08 18:20 UTC, fromanywhere commented on todo_style.css
> +    flex-grow: 1;
зачем ему 1?

2022-12-08 18:20 UTC, fromanywhere commented on todo_style.css
> +    margin: 0 0 0 -70px;
Неясно, почему 70

2022-12-08 19:51 UTC, NIKITry commented on todo_style.css
> +    min-height: 64px;
а что с этим можно сделать, я не особо понимаю, потому что в дз по css не входит написание текста в таски, я поэтому и не мог это оценить сам

2022-12-08 19:53 UTC, NIKITry commented on todo_style.css
> +    flex-grow: 10;
нет, если поставить 1, то сместятся кружки, я не очень понимаю, что можно сделать, чтобы работало с параметром 1

2022-12-08 19:54 UTC, NIKITry commented on todo_style.css
> +    border: 1.4px  #f2f2f2 solid ;
убрал, поставил 1

2022-12-08 19:56 UTC, NIKITry commented on todo_style.css
> +    margin: 0 0 0 -70px;
при 70 кружки занимают такое положение, что не видно чекбоксов, но и кружки не сильно прижимаются к краю

2022-12-08 19:57 UTC, NIKITry commented on todo_style.css
> +    display: none;
не очень понимаю, как пофиксить, тоже margin?

2022-12-08 20:05 UTC, NIKITry commented on todo_style.css
> +    display: none;
гляньте последний коммит, но не пойму, как марджинами убрать вообще из видимости радио-кнопки

2022-12-08 20:06 UTC, NIKITry commented on todo_style.css
> +    text-indent: -999px;
исправил на 9999px

2022-12-08 20:46 UTC, NIKITry commented on todo_style.css
> +    min-height: 64px;
вроде исправил, посмотрите

2022-12-08 20:47 UTC, NIKITry commented on todo_style.css
> +    flex-grow: 10;
переделал немного структуру, теперь вроде позиционирование в норме

2022-12-08 20:48 UTC, NIKITry commented on todo_style.css
> +    flex-grow: 1;
не нужен, стоит дефолтное

2022-12-12 14:42 UTC, fromanywhere approved these changes
Зачтено за приложенные усилия

2022-12-12 14:42 UTC, fromanywhere commented on todo_style.css
> +    text-indent: -999px;
нет, так и осталось

2022-12-12 14:44 UTC, merged